[platformio]
default_envs = i2c_scanner

[env]
platform = atmelavr
board = nanoatmega328
framework = arduino
; monitor_speed = 57600
; upload_speed = 57600
build_flags =
  -Wall
  -Wextra

[env:i2c_scanner]
build_src_filter = +<01_i2c_scanner.cpp>

[env:lcd1602]
build_src_filter = +<02_lcd1602.cpp>
lib_deps =
  duinoWitchery/hd44780 @ ^1.3.2

[env:rotary_encoder]
build_src_filter = +<03_rotary_encoder.cpp>

[env:max6675]
build_src_filter = +<04_max6675.cpp>
lib_deps =
  adafruit/MAX6675 library @ ^1.1.2

[env:ssr_driver]
build_src_filter = +<05_ssr_driver.cpp>

[env:buzzer]
build_src_filter = +<06_buzzer.cpp>

[env:low_voltage_integration]
build_src_filter = +<07_low_voltage_integration.cpp>
lib_deps =
  adafruit/MAX6675 library @ ^1.1.2
  duinoWitchery/hd44780 @ ^1.3.2
